embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/test_chamber/models/cube.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material\"\n"
  "  material: \"/test_chamber/materials/grey_box.material\"\n"
  "  textures {\n"
  "    sampler: \"wall\"\n"
  "    texture: \"/test_chamber/textures/dark.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"floor\"\n"
  "    texture: \"/test_chamber/textures/green.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"ceiling\"\n"
  "    texture: \"/test_chamber/textures/red.png\"\n"
  "  }\n"
  "}\n"
  ""
}
